### ISSUE TITLE
Config file for Gravitational Waves missing

### ISSUE THREAD

**Issue by macio232** [montefiore-ai/balanced-nre#5]
Hi,

When I try to run the Gravitational Waves pipeline, I get the following error: 
```
ValueError: Cannot open file [...]/site-packages/hypothesis/benchmark/gravitational_waves/config_file.ini
```
because the file doesn't exist. I know this is an issue related to `hypothesis` but I decided to ask here to give a better context.

Thank you in advance :)
macio232

**Comment by JoeriHermans** [comment]
https://github.com/montefiore-ai/hypothesis/blob/0.4.0/hypothesis/benchmark/gravitational_waves/config_file.ini

Should have been there. Probably because we cloned the repo, and manually ran `pip install -e .`. Can you check if this works for you? I'll close the issue if it's OK.

**Comment by macio232** [comment]
Yes, the file is where it is supposed to be when installing from the source in editable mode. Thank you!
