### ISSUE TITLE
RecursionError: maximum recursion depth exceeded while calling a Python object despite sys.setrecursionlimit(10000)

### ISSUE THREAD

**Issue by macio232** [montefiore-ai/balanced-nre#6]
Hi,

In `pipeline.py`, there is a `sys.setrecursionlimit(10000)` line at the top to avoid `RecursionError`. However, the error still appears when running the pipeline in standard mode (not debug). I tried increasing the recursion limit, but this eventually results in a `Segmentation fault`.

What part of the code uses such a long recursion? Is there any way I can run the code on my hardware?

Thank you in advance :)
macio232

**Comment by macio232** [comment]
Ok, increasing the system stack size with `ulimit -s <new_value>` did the job.

**Comment by JoeriHermans** [comment]
Yeah, this `awflow` thing was actually an initial prototype to make our lives a bit easier. Would suggest (if you want to of course) using https://github.com/francois-rozet/dawgz in the future. Much better.
